/**
 * Pricing Data
 * Centralized pricing tier configuration.
 */

import type { PricingTier } from './PricingCard';

export const pricingTiers: PricingTier[] = [
  {
    name: 'Starter',
    price: '$49',
    period: '/month',
    tagline: 'Perfect for new venues',
    description: 'Everything you need to start accepting bookings.',
    badge: null,
    features: [
      { text: '30 bookings/month included', highlight: true },
      { text: '2 credits per booking charge', highlight: false },
      { text: '3 rooms or activities', highlight: false },
      { text: 'Online booking widget', highlight: false },
      { text: 'Basic calendar management', highlight: false },
      { text: 'Payment processing', highlight: false },
      { text: 'Email support (24hr response)', highlight: false },
    ],
    cta: 'Start Free Trial',
    ctaVariant: 'secondary',
    popular: false,
    savings: null,
    outcome: 'Save 10+ hours/week on manual booking management',
  },
  {
    name: 'Professional',
    price: '$99',
    period: '/month',
    tagline: 'For growing businesses',
    description: 'Advanced automation and AI assistance.',
    badge: 'Most Popular',
    features: [
      { text: '70 bookings/month included', highlight: true },
      { text: 'Unlimited rooms & activities', highlight: false },
      { text: 'AI chat assistant (24/7)', highlight: true },
      { text: 'Advanced analytics & reports', highlight: true },
      { text: 'QR code check-in', highlight: false },
      { text: 'Custom branding & domain', highlight: false },
      { text: 'Priority support (4hr response)', highlight: false },
    ],
    cta: 'Start Free Trial',
    ctaVariant: 'primary',
    popular: true,
    savings: 'Save $1,200/mo vs hiring staff',
    outcome: 'Increase revenue by 40% with 24/7 AI booking',
  },
  {
    name: 'Business',
    price: '$299',
    period: '/month',
    tagline: 'For high-volume operations',
    description: 'Complete automation with AI phone and marketing.',
    badge: null,
    features: [
      { text: '100 bookings/month included', highlight: true },
      { text: 'AI Call Agents', highlight: true },
      { text: 'Email & SMS marketing', highlight: true },
      { text: 'Referral system', highlight: true },
      { text: 'Review management', highlight: true },
      { text: 'Digital Waivers', highlight: true },
      { text: 'Phone support (1hr response)', highlight: false },
    ],
    cta: 'Contact Sales',
    ctaVariant: 'secondary',
    popular: false,
    savings: 'Save $3,500/mo vs full-time staff',
    outcome: 'Handle 3x more bookings with same team size',
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    period: '',
    tagline: 'For large-scale operations',
    description: 'Unlimited everything with custom AI training.',
    badge: 'Ultimate Power',
    features: [
      { text: 'Unlimited bookings & locations', highlight: true },
      { text: 'Multi-location management', highlight: true },
      { text: 'White-label solution', highlight: true },
      { text: 'Custom AI model training', highlight: true },
      { text: 'Dedicated infrastructure', highlight: true },
      { text: '99.99% uptime guarantee', highlight: false },
      { text: 'Custom contracts & invoicing', highlight: false },
    ],
    cta: 'Contact Sales',
    ctaVariant: 'secondary',
    popular: false,
    savings: 'Custom pricing for your scale',
    outcome: 'Enterprise-grade reliability for mission-critical operations',
  },
];
